"""add user model

Revision ID: 75261d1af841
Revises: cff81282c23b
Create Date: 2026-05-25 12:36:21.215749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75261d1af841'
down_revision = 'cff81282c23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=228), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
        batch_op.alter_column('deadline',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)

    op.drop_table('user')
    # ### end Alembic commands ###
