"""empty message

Revision ID: f495aa55c9b3
Revises: 
Create Date: 2026-05-18 09:57:41.470836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f495aa55c9b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_name', sa.String(length=100), nullable=False),
    sa.Column('contacts', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=30), nullable=False),
    sa.Column('deal_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
