"""add user role

Revision ID: 829aab6c4184
Revises: 5c00d59987bb
Create Date: 2026-06-04 20:03:45.396285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '829aab6c4184'
down_revision: Union[str, Sequence[str], None] = '5c00d59987bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "users",
    sa.Column(
        "role",
        sa.String(length=50),
        nullable=False,
        server_default="admin"
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
