"""add deal owner

Revision ID: 917eb34e238c
Revises: 346ac77d8eac
Create Date: 2026-06-06 14:43:27.309921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917eb34e238c'
down_revision: Union[str, Sequence[str], None] = '346ac77d8eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deals', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('deals', 'owner_id')
    # ### end Alembic commands ###
